export enum AuthType{
  REGISTER_START='[AUTH] REGISTER START',
  REGISTER_SUCCESS='[AUTH] REGISTER SUCCESS',
  REGISTER_ERROR='[AUTH] REGISTER ERROR',

  LOGIN_START='[AUTH] LOGIN START',
  LOGIN_SUCCESS='[AUTH] LOGIN SUCCESS',
  LOGIN_ERROR='[AUTH] LOGIN ERROR',

}