export enum HomeActionType{
  GLOBAL_START='[HOME] GLOBAL_START',
  GLOBAL_SUCCESS='[HOME] GLOBAL_SUCCES',
  GLOBAL_ERROR='[HOME] GLOBAL_ERROR',

  YOUR_START='[HOME] YOUR_START',
  YOUR_SUCCESS='[HOME] YOUR_SUCCESS',
  YOUR_ERROR='[HOME] YOUR_ERROR',
}