export enum HomeActionType{
  GLOBAL_START='[HOME] GLOBAL_START',
  GLOBAL_SUCCESS='[HOME] GLOBAL_SUCCES',
  GLOBAL_ERROR='[HOME] GLOBAL_ERROR',

  YOUR_START='[HOME] YOUR_START',
  YOUR_SUCCESS='[HOME] YOUR_SUCCESS',
  YOUR_ERROR='[HOME] YOUR_ERROR',

  ARTICLE_START='[HOME] ARTICLE_START',
  ARTICLE_SUCCESS='[HOME] ARTICLE_SUCCESS',
  ARTICLE_ERROR='[HOME] ARTICLE_ERROR',
}